### ISSUE TITLE
[버그] 로그아웃 후 헤더 변화 없음  

### ISSUE THREAD

**Issue by heechul94** [where-we-meet/owl#27]
📕 Issue Feature 
로그아웃 후 헤더의 UI가 로그인 UI 그대로 보여지는 현상이 있습니다.

🧾Todo
- [x] 유저 상태에 맞는 헤더 UI 보여주기

🖼️ 스크린샷

![owl- 헤더 UI 이슈](https://github.com/where-we-meet/owl/assets/100992153/118c5a58-50fb-4993-aed4-ba306b0c7725)

**Comment by lauichan** [comment]
ㅠㅠㅠ
